export const INIT_CUSTOMERS = "INIT_CUSTOMERS";
export const FETCH_CUSTOMER = "FETCH_CUSTOMER";
export const SET_CUSTOMER = "SET_CUSTOMER";
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const INIT_CATEGORIES = "INIT_CATEGORIES";
export const INIT_PAYMENT = "INIT_PAYMENT";
export const CHANGE_PAGE = "CHANGE_PAGE";

export const CHANGE_INPUT = "CHANGE_INPUT";
export const CHANGE_ERROR = "CHANGE_ERROR";

export const INIT_SUBMIT_FORM = "INIT_SUBMIT_FORM";
export const SUCCESS_SUBMIT_FORM = "SUCCESS_SUBMIT_FORM";
export const SUBMIT_VALIDATION_ERROR = "SUBMIT_VALIDATION_ERROR";
export const FAIL_SUBMIT_FORM = "FAIL_SUBMIT_FORM";

export const SORT_COLUMN = "SORT_COLUMN";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const SET_PROPERTY = "SET_PROPERTY";
export const SEARCH_QUERY = "SEARCH_QUERY";

export const INIT_LOGIN_USER = "INIT_LOGIN_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const FAIL_LOGIN_USER = "FAIL_LOGIN_USER";
