// CUSTOMER
export const INIT_CUSTOMERS = "INIT_CUSTOMERS";
export const FETCH_CUSTOMER = "FETCH_CUSTOMER";
export const SET_CUSTOMER = "SET_CUSTOMER";
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const INIT_CATEGORIES = "INIT_CATEGORIES";
export const INIT_PAYMENT = "INIT_PAYMENT";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const SORT_COLUMN = "SORT_COLUMN";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const SET_PROPERTY = "SET_PROPERTY";
export const SEARCH_QUERY = "SEARCH_QUERY";
export const CHANGE_INPUT = "CHANGE_INPUT";
export const CHANGE_ERROR = "CHANGE_ERROR";
export const INIT_SUBMIT_FORM = "INIT_SUBMIT_FORM";
export const SUCCESS_SUBMIT_FORM = "SUCCESS_SUBMIT_FORM";
export const SUBMIT_VALIDATION_ERROR = "SUBMIT_VALIDATION_ERROR";
export const FAIL_SUBMIT_FORM = "FAIL_SUBMIT_FORM";

// AUTH
export const CHANGE_INPUTS = "CHANGE_INPUTS";
export const CHANGE_ERRORS = "CHANGE_ERRORS";
export const INIT_LOGIN_USER = "INIT_LOGIN_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const FAIL_LOGIN_USER = "FAIL_LOGIN_USER";

// USER CATEGORY
export const INIT_USER_CATEGORIES = "INIT_USER_CATEGORIES";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const SET_CATEGORY = "SET_CATEGORY";
export const CHANGE_CATEGORY_PAGE = "CHANGE_CATEGORY_PAGE";
export const SORT_CATEGORY_COLUMN = "SORT_CATEGORY_COLUMN";
export const OPEN_CATEGORY_MODAL = "OPEN_CATEGORY_MODAL";
export const CLOSE_CATEGORY_MODAL = "CLOSE_CATEGORY_MODAL";
export const SET_CATEGORY_PROPERTY = "SET_CATEGORY_PROPERTY";
export const SEARCH_CATEGORY_QUERY = "SEARCH_CATEGORY_QUERY";
export const CHANGE_CATEGORY_INPUT = "CHANGE_CATEGORY_INPUT";
export const CHANGE_CATEGORY_ERROR = "CHANGE_CATEGORY_ERROR";
export const INIT_SUBMIT_CATEGORY_FORM = "INIT_SUBMIT_CATEGORY_FORM";
export const SUCCESS_SUBMIT_CATEGORY_FORM = "SUCCESS_SUBMIT_CATEGORY_FORM";
export const SUBMIT_CATEGORY_VALIDATION_ERROR =
  "SUBMIT_CATEGORY_VALIDATION_ERROR";
export const FAIL_SUBMIT_CATEGORY_FORM = "FAIL_SUBMIT_CATEGORY_FORM";

// ORDER

export const SET_CATEGORIES_FOR_ORDER = "SET_CATEGORIES_FOR_ORDER";
export const INPUT_CHANGE_FOR_ORDER = "INPUT_CHANGE_FOR_ORDER";
export const CHANGE_ERROR_FOR_ORDER = "CHANGE_ERROR_FOR_ORDER";
export const SET_CUSTOMERS_FOR_ORDER = "SET_CUSTOMERS_FOR_ORDER";
export const SET_PRODUCT_PRICE_FOR_ORDER = "SET_PRODUCT_PRICE_FOR_ORDER";
export const INPUT_CHANGE_FOR_ORDER_ITEMS = "INPUT_CHANGE_FOR_ORDER_ITEMS";
export const CALCULATE_TOTAL_ORDER = "CALCULATE_TOTAL_ORDER";
export const INIT_SUBMIT_FORM_ORDER = "INIT_SUBMIT_FORM_ORDER";
export const SUCCESS_SUBMIT_FORM_ORDER = "SUCCESS_SUBMIT_FORM_ORDER";
export const FAIL_SUBMIT_FORM_ORDER = "FAIL_SUBMIT_FORM_ORDER";
